# Generated by Django 3.0.4 on 2020-05-02 15:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ObdCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=50, verbose_name='author')),
                ('comment_text', models.TextField(max_length=500, verbose_name='comment text')),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='date published')),
                ('car_model', models.CharField(max_length=50, verbose_name='car model')),
                ('obd_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subaruhelp.ObdCode')),
            ],
        ),
    ]
